PR for software review.
sparkfun/SparkFun_AS7331_Arduino_Library pull request #1
Opened 2023-11-28 19:10 UTC by SFE-Brudnerd

2023-11-28 19:13 UTC, SFE-Brudnerd commented
Please note that the "sfe_xxx" files are based on the upcoming sparkfun toolkit release for I2C. The intent is to delete these once that comes out so that we can use that toolkit.

2023-11-30 20:15 UTC, gigapod requested changes
Overall, this needs refactoring.

General notes:
- Too complicated - needs to simplify in the implementation. 
      - Not a template
      - Too many types right now. 
      - Use instance variables - not a heap of structs for things (hard to follow)
- Comment the Code - not just methods headers. In line comments is ***FAR*** more valuable the header comments.  
     -- Style note - Use dividing lines between methods and important sections - really helps when scrolling through a file.- or using a mini map
- Run the code through the formatter.  
- Lets just pick a version of the toolkit library and publish it! 
      - Start with what we have hear - with fixes - and go!

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +/// @brief Measures structure to hold return values.
I don't agree with this concept of using a variety of structs to start state and values. Some times this will make sense, if its in context of the underlying device / thing you're trying ton control . 

All this is doing: 
- You lose context on the instance data - it's buried down a level  in some struct
- You can't use proper c++ constructor initialization on values if needed
- Using Const struct to store default - leaves a 'const struct' always dangling around in your program space -- consuming memory.  AND the defaults are defined out somewhere out of context in the code. 

Keep state in instance/member variables. Group in struct if it makes sense for the context of the data/state being modeled - or used external of this driver. 

Setting defaults - do them in the constructor (if there is no reset capability), or create "reset" method. No dangling constants.

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +                .uvb = (uint16_t)(-1),
What is (uint16_t)(-1)? No context. If it's some special number, make it a macro and name it so it makes sense.

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +const sfeAS7331_config_t configDefault = {
No, make a method to init state

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +template<typename sfeBusDevice, typename sfeBusDeviceSettings>
This should NOT be a Template  it should be a class.  There's only need for one class definition, using a template can make N classes - although we're only creating one for this driver.

For our core drivers, specialization is provided by
- Using a bus INTERFACE - so the bus device is abstracted and passed by that caller/user of the driver. 
- Sub-classing the core class.

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            _state = stateDefault;
Minimize struct, create reset/init methods if performed more than once.
Use C++ constructor init functional  aka:
```c++
class  cow
{
    float * _var1;
    bool _var2;
    char* _var3; 
    
public:
    cow(): _var1{nullptr}, _var2{true}, _var3{"cow")
    {}
} ;

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            _sfeBus->begin();
Should this be here -- more of a question on the underlying bus impl -- every driver shouldn't call being for the bus, shouldn't be bus figure this out?

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +
Whats happening here -- more comments in the code

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +        int8_t writeRegister(const uint8_t offset, const uint8_t *data, const uint16_t length = 1)
Wrong - why aren't the methods that need to use the bus  using it directly - NO need to redirect to another methods - waste of vtable space.

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +                _state = stateDefault;
Comment the code/impl -Describe what's taking place, why something is happing ...etc.

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            osr.ss = _state.ss;
What's happening here? comments!

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            regs[0] = creg1.byte;
These seems overtly complicated - cared a struct, set some data, do some union magic. Can something be setup to just send the values correctly in the registers. Right now, very hard to follow - I'm jumping around to the register struct defs ....etc.

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            calculateConversionFactors();
What's do I expect to happen after this call - is some side-effect taking place?

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            if(_state.mmode != measMode)
What is happening here?

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +        int8_t setCommunicationBus(sfeBusDevice *theBus, sfeBusDeviceSettings *deviceSettings)
Seems like these methods can be collapsed to one...

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            if(!_devSettings)
Comments. Also, in general you shouldn't depend on the side-effects of some method to populate instance data per se. That said, you do see a "init()" method to do this, and then methods/variables to check that the class is "initialized". Where "initialization" ensures the device is ready to use.

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            _state = stateDefault;
Methods, not dangling const structs

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            measures.temperature = convertRawTempToTempC((uint16_t)(((uint16_t)tempRaw[1] << 8 | tempRaw[0])));
Comments on the bit shifts/frobbing.

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            if(_state.mmode == MEAS_MODE_SYND) {
Comments on what's happening

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +
Comments

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +                float divFactor = (bool)_config.dividerEnabled ? (float)(1 << (1+_config.dividerRange)) : 1.0f;
Comments

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            if(_state.mmode == MEAS_MODE_SYND) {
General NOTE - This code needs to be run through the C++ formatter we're using. The {} are in the wrong place

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +                float convFactor = ((float)measures.outputConversionTime)*((float)(1 << (11 - _config.sensorGain)));
Comments

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            if(_state.mmode == MEAS_MODE_SYND) {
Comments

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +        /// @return internal state struct.
Why is this needed? This completely breaks encapsulation.

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +        sfeAS7331_config_t getConfig(void)
Breaks encapsulation. Right? And this is copying a lot of values - shouldn't something more data efficient be used - pass by reference as a parameter?

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +            result = getCReg1(&creg1);
Comments

2023-11-30 20:15 UTC, gigapod commented on src/SparkFun_AS7331.h
> +        {
Comments

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +
General:

- Each of these types, values need comments to describe what they are and when used. 

And do we really need all these types - especially for things that only have two states - just have the methods use a bool or something. 

Overall too many enums/ types.

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +typedef enum {
BOOL

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +typedef enum {
Use a bool

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +typedef enum {
Bool

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +    // 0b00X invalid
Two modes, why not bool

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +typedef enum {
BOOL

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +typedef enum {
BOOL

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +typedef enum {
BOOL

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +typedef enum {
BOOL

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +#define SFE_AS7331_REGISTER_CFG_OSR 0x00
Do these map to underlying bit state/register of the device? That should be outlined here - and define why we're using the bit field.

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +#define SFE_AS7331_REGISTER_CFG_BREAK 0x09
Why these types?

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +typedef union {
Maps too underling register?

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +typedef union {
Too many types. - ether make one to uin8 to word union and use everywhere, or just make a macro that does the needed bit shifts.  All these types are confusing

2023-11-30 20:15 UTC, gigapod commented on src/sfe_as7331_registers.h
> +/*
General Comment - skip the use of this registers header - just put the types in the standard header. This is just confusing - you lose context of the types with the class definition.

2023-11-30 20:15 UTC, gigapod commented on src/sfe_bus.h
> +  SPDX-License-Identifier: MIT
Let's just skip including this and make a working version of the toolkit library and publishing it.

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c.h
> +  public:
Do we want public members,  or do we want values accessed by methods (maintain encapsulation)??  Basically, is some some level of control of these values ?

If we want public, just make it a struct.

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.cpp
> +            result = _mapError(_i2cBus->endTransmission(false));
Why call maperror here - you're still in arduino space. Why not only call it when making the return call. One less function call to make.

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.cpp
> +    SFEBusDevSettingsI2C *pAddr = (SFEBusDevSettingsI2C *)devSettings;
Why cast? Does I2C vs SPI device settings differ?  Doing a cast here indicates to me the design is wrong.  Either settings needs to be the same between devices, or enable a specialization (subclassing). And the bus implementation methods desired around that.  This method - should be receiving a I2C settings value that verified at compile time.  The cast is doing zero type checking.

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.cpp
> +    int8_t result = _mapError(_i2cBus->endTransmission(false));
NO MapError here - use normal Arduino Error checking - same the function call cycles.

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.cpp
> +    SFEBusDevSettingsI2C *pAddr = (SFEBusDevSettingsI2C *)devSettings;
See above

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.cpp
> +    SFEBusDevSettingsI2C *pAddr = (SFEBusDevSettingsI2C *)devSettings;
See earlier comment

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.cpp
> +    int8_t result = _mapError(_i2cBus->endTransmission(false));
no mapError here

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.cpp
> +{
Why does set return a value? Can this fail?

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.cpp
> +int8_t SFEBusArduinoI2C::getBufferSize(uint32_t *bufferSize)
No nullptr check - this method can go *boom*.

Use a reference - 
```C++
 getBufferSize(uint32_t &bufferSize)
```

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.cpp
> +    *frequency = _busFrequency;
No nullptr check -  FAIL.

use a reference as noted above

2023-11-30 20:15 UTC, gigapod commented on src/sfe_i2c_arduino.h
> +    int8_t ping(const SFEBusDevSettings *devSettings);
General Design question we need to answer:

Does the bus have state, or is stateless? 
- If it's stateless, then yes, lets' bass in settings with the read/write calls.
- If it has state - add a get/set settings call and pull out the settings parameters out of the read/write calls.

I say it has state - most of the time the settings don't change, so why should I have to pass that pointer in every time I make the call??  ... annoying and something else I need to manage 

Let's talk this one through

2023-11-30 20:16 UTC, gigapod commented
When we're all in the office, lets walk/talk through the comments I made. I believe this would be helpful.

2023-11-30 23:50 UTC, sfe-SparkFro requested changes

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        }
Could combine these into a single method, where the bus and device setting pointers default to `nullptr`. Eg:

`begin(uint8_t deviceAddress = AS7331_ADDR_DEFAULT, sfeBusDevice *theBus = nullptr, sfeBusDeviceSettings *devSettings = nullptr)`

Then just call `setCommunicationBus(theBus, devSettings)`, which is already written to handle `nullptr` defaults

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            _sfeBus->begin();
Device libraries should not begin the I2C bus, the user sketch should do that. That helps avoid beginning the bus multiple times if the user has multiple devices connected.

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +                return false;
Check if it's connected _before_ trying to reset it. If there's somehow another device on the bus with the same address, who knows what that'd do!

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +                return reset();
If `runSoftReset` is `true`, shouldn't the rest of the code here still run as long as `reset()` is successful?

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            }
Shouldn't this be done regardless of `runSoftReset`? Or perhaps only if `runSoftReset` is `true`?

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        }
Style question - should private member functions also be prefixed with an underscore?

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        static constexpr float fsrC = 169984.0; // Full Scale Resolution for the UVC sensor.
Why not `#define` these?

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +                return false;
Why are these being re-written to the device just after they got read from the device?

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        bool startMeasurement(const as7331_meas_mode_t measMode = MEAS_MODE_CONT, bool startMeasure = false)
I don't think `startMeasurement` is the right name for this, maybe something like `setMeasurementMode`?

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        }
Feels a bit weird for the comm methods to be here, at the top (or bottom) seems more appropriate to me

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            measures.temperature = convertRawTempToTempC((uint16_t)(((uint16_t)tempRaw[1] << 8 | tempRaw[0])));
Can remove the leftmost `uint16_t` cast, it's already a `uint16_t`

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            }
This same code pattern appears multiple times, put it into a single function call

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +                measures.uva = (float)((uint16_t)(((uint16_t)uvaRaw[1]) << 8 | uvaRaw[0])-1.0f)*_conversionA;
This is really hard to read and understand what is happening with all the casting and everything being on only a few lines. This should be split into more lines with comments explaining what's going on.

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            measures.outputConversionTime = (uint32_t)(((uint32_t)tconvRaw[3] << 24) | ((uint32_t)tconvRaw[2] << 16) | ((uint32_t)tconvRaw[1] << 8) | tconvRaw[0]);
Not a fan of long lines of code like this, put it onto multiple lines. Rule of thumb, keep stuff within 80 characters

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +                calculateConversionFactors();
Shouldn't this be done regardless?

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        int8_t setDigitalDivider(const as7331_divider_val_t divider, const bool setEnableDiv = false)
Why default `setEnableDiv` to false? If someone is setting the divider value, surely they'd want that to actually do something, right?

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        int8_t getPowerState(as7331_power_state_t *pd)
Check for `nullptr` (also in all relevant methods below)

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        int8_t setPowerState(const as7331_power_state_t pd = POWER_DOWN_DISABLE)
Why does this default to power down? In fact, why default to anything? The method name doesn't imply anything that would make a user assume there's a default, and especially not defaulting to power down

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            *pd = _state.pd;
Since you have a local copy, why not just return the value from there? The local copy should always be up to date, so reading the register contents is just a waste of time (same for all relevant getters below)

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            _conversionC = fsrC/((float)(1 << (11 - _config.sensorGain)))/((float)(1 << _config.conversionTime))/((float)(1024.0 * (1 << _config.cclk)))*divFactor;
The denominator is the same in each of these, calculate it once

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +} sfeAS7331_state_t;
I don't agree with keeping a local copy of all these things. Some are fine (eg. you need `sensorGain` for every measurement, may as well keep a copy), but others are completely unused outside of setters/getters and just take extra memory (eg. `readyPinMode`, `enableTempConv`, `sb`, `ss`, etc.)

2023-11-30 23:50 UTC, sfe-SparkFro commented on src/sfe_as7331_registers.h
> +// read-only and 16 bits long, except OUTCONV, which is 24 bits long.
Wait a minute, the registers change depending on what mode it's in? Wild. In that case, every method in `SparkFun_AS7331.h` needs to check `_state.opMode` (is that the right one?) before reading/writing to any registers

2023-12-01 18:08 UTC, edspark reviewed
I'm going to hold off on my review, pending changes requested by Kirk.

2023-12-01 18:25 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +} sfeAS7331_state_t;
Based on the way the sensor is designed you can't read config registers while it's in measurement mode, so the intent was to keep a local copy of state so that you don't have to interrupt the sensor, change mode, read register, change mode back and restart measurement just to know how the sensor is configured. However, after talking to Kirk I'm going to make them member variables rather than storing them in structs. Structs made more sense in my mind for keeping like items together but it adds an unnecessary layer of abstraction.

2023-12-01 18:26 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +                .uvb = (uint16_t)(-1),
No special number, just was a way to have a default invalid measurement so you knew that it was garbage data.

2023-12-01 18:29 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            _sfeBus->begin();
Agreed, I suppose that requires the bus to be started prior to running this begin then, since the next call to init sends data over the line.

2023-12-01 18:29 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            _sfeBus->begin();
Agreed, see my response to Dryw.

2023-12-01 18:34 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +                return false;
This is a bit of a chicken and egg problem. I had that originally, but if the sensor is in measurement mode when init is called (ex pressing the reset button when running an example) and the device doesn't lose power, it won't respond accurately to the isConnected function since that register isn't available in measurement mode. This ensures the device is in configuration mode before trying to get the register.

Another way to solve this might be to send the command to put the device in config mode then interrogate the device ID, but that requires the device to be there.

2023-12-01 18:35 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            _sfeBus->begin();
Yes, that's how all our examples are written. Something along the lines of:

```
setup()
{
  Serial.begin();
  Serial.println("Example 1");
  Wire.begin(); // Or now the SFE bus device, which will just have Wire passed in
  mySensor.begin();
}
```

2023-12-01 18:37 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +                return reset();
Yeah good point, I think that was my intent. I should just call reset and save the output to a variable rather than returning it. Reset does cover a good bit of what follows, but not all of it.

2023-12-01 18:38 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            }
This is also done in the reset function, so I didn't want it to happen twice, but it needed to happen at least once.

2023-12-01 18:45 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +                return false;
I was following read->mod->write since not all the values are being written. I didn't want to change the parts that aren't.

2023-12-01 18:49 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            calculateConversionFactors();
Will comment this, but this just recalculates the sensor conversion factors based on the changes that affect it's value. That way it only needs to be calculated once when it's being modified, and not every time it's run.

2023-12-01 18:51 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        bool startMeasurement(const as7331_meas_mode_t measMode = MEAS_MODE_CONT, bool startMeasure = false)
`setMeasurementMode` already exists, but agreed that `startMeasurement` isn't quite right. It does more than just change it to measurement mode, it makes sure it's not shut down or in standby, changes the operation state, then begins measuring if desired. Perhaps `stageMeasurement` or `prepareMeasurement`?

2023-12-01 18:52 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            if(_state.mmode != measMode)
This is mainly to prevent unnecessary writes, it won't write it if it's not needing to change based off the internal state.

2023-12-01 18:54 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        }
Agreed, I had it higher but ended up adding in functions and just put them in out of place above this.

2023-12-01 18:57 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            }
It does but with different measurements, so that sub function will basically need to be a big switch statement. But agreed it could look cleaner.

2023-12-01 19:00 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        /// @return internal state struct.
It's probably not, was more a convenience so you didn't have to run multiple methods if you wanted it all. There's no way to set the state all at once though, so it only breaks one way :)

2023-12-01 19:00 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        sfeAS7331_config_t getConfig(void)
It's probably not needed, was more a convenience so you didn't have to run multiple methods if you wanted it all. There's no way to set the configuration all at once though, so it only breaks one way :). Agreed on passing by reference.

2023-12-01 19:02 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        int8_t setDigitalDivider(const as7331_divider_val_t divider, const bool setEnableDiv = false)
Not necessarily, they may want to be able to change it without enabling it so they can use it later. Though I suppose that would just invert the default requiring them to always write false unless they want it to be set. There's also a function that only enables the divider.

2023-12-01 19:03 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +                calculateConversionFactors();
It's done in the `setEnableDivider` function too, so I didn't want it to run twice.

2023-12-01 19:36 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            *pd = _state.pd;
I suppose these ones would be good as private/protected methods, since you need to get the value at some point.

2023-12-01 19:36 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        int8_t setPowerState(const as7331_power_state_t pd = POWER_DOWN_DISABLE)
Was a convenience factor, but agree that it doesn't make sense.

2023-12-01 19:39 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        }
According to the [style guide](https://github.com/sparkfun/.github/blob/main/SFECodeStyleGuide.md) no.

2023-12-01 19:40 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        static constexpr float fsrC = 169984.0; // Full Scale Resolution for the UVC sensor.
They're specific to the class so I didn't want them to be global. They do need to be _fsr* though.

2023-12-01 19:52 UTC, SFE-Brudnerd commented on src/sfe_as7331_registers.h
> +#define SFE_AS7331_REGISTER_CFG_OSR 0x00
Yes and can do.

2023-12-01 19:55 UTC, SFE-Brudnerd commented on src/sfe_as7331_registers.h
> +// read-only and 16 bits long, except OUTCONV, which is 24 bits long.
Yep, I hate it but it is what it is. And agreed. I had notes in to do it, but I can't remember why I didn't put them in.

2023-12-01 19:56 UTC, SFE-Brudnerd commented on src/sfe_i2c_arduino.cpp
> +            result = _mapError(_i2cBus->endTransmission(false));
mapError maps Wire errors to SFE_BUS errors.

2023-12-01 19:57 UTC, SFE-Brudnerd commented on src/sfe_i2c_arduino.cpp
> +{
it probably could, but further down the line. Probably needs limiting here and returning a warning if it was saturated.

2023-12-01 23:05 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +                return false;
Oh man, this sensor is driving me nuts with its registers changing based on what mode it's in lol. Ok, fair enough, I'd just leave it as is then.

2023-12-01 23:06 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +                return false;
Yeah I definitely wasted over an hour trying to figure out why I couldn't reset the device properly :)

2023-12-01 23:09 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            }
Sorry, I didn't write this clearly. In line 210, you've got `return`, meaning if `runSoftReset` is true, none of the rest of the code will run. But it probably should run, as long as `reset()` is successful, right? Or am I misunderstanding what this function is meant to do?

2023-12-01 23:11 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            }
Yes, you address this in the previous comment and I responded there that I agree it does need to continue. The default assignments happen inside the `reset()` function too, so if the `reset()` wasn't going to happen, I still wanted those to be set. But I didn't want them to be set twice.

2023-12-01 23:20 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +                return false;
I'm looking at this closer now, and this restores all non-reserved bits to their defaults. I guess I'm not understanding why you'd need to do this without just resetting the sensor?

Also, this method is only called by `init()`, which already called `reset()`, so I just don't really see the point of this method. Can it just be deleted?

2023-12-01 23:30 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +                return false;
Not all the reserved bits are always 0. This was a convenience function as the user could want to reset the device to default. But now thinking about it, I can move the majority of this to the init function, and the user can just call the reset function.

2023-12-01 23:35 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        bool startMeasurement(const as7331_meas_mode_t measMode = MEAS_MODE_CONT, bool startMeasure = false)
> it makes sure it's not shut down or in standby

Shouldn't the current implementation of `setMeasurementMode()` do that? What if a user calls it while in shutdown or standby?

Also, shouldn't `setStandbyMode(STANDBY_DISABLED)` only be called if `_state.sb == STANDBY_ENABLED`?

The more I look at this, the more I think `startMeasurement()` isn't needed; a user should just call `setMeasurementMode()` (which should perform all the same checks) and `setStartStateMode()` separately, which is exactly what your examples do anyways.

2023-12-01 23:42 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            }
What about something like this? No big switch needed

```
int8_t readRawUV(uint8_t address, float* uv) // This should be private
{
    uint8_t uvaRaw[2];

    int8_t result = readRegister(address, uvRaw, 2U);

    if(SFE_BUS_OK != result)
        return result;

    if(_state.mmode == MEAS_MODE_SYND) {
        result = readOutConv();

        if(SFE_BUS_OK != result)
            return result;

        float divFactor = (bool)_config.dividerEnabled ? (float)(1 << (1+_config.dividerRange)) : 1.0f;
        float convFactor = ((float)measures.outputConversionTime)*((float)(1 << (11 - _config.sensorGain)));
        *uv = (float)((uint16_t)(((uint16_t)uvRaw[1]) << 8 | uvRaw[0])-1.0f)*fsrA*divFactor/convFactor;
    }
    else {
        *uv = (float)((uint16_t)(((uint16_t)uvRaw[1]) << 8 | uvRaw[0])-1.0f)*_conversionA;
    }
    
    return SFE_BUS_OK;
}

int8_t readUVA(void)
{
    return readRawUV(SFE_AS7331_REGISTER_MEAS_MRES1, &measures.uva);
}

int8_t readUVB(void)
{
    return readRawUV(SFE_AS7331_REGISTER_MEAS_MRES2, &measures.uvb);
}

int8_t readUVC(void)
{
    return readRawUV(SFE_AS7331_REGISTER_MEAS_MRES3, &measures.uvc);
}
```

2023-12-01 23:42 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        bool startMeasurement(const as7331_meas_mode_t measMode = MEAS_MODE_CONT, bool startMeasure = false)
I encourage you to look at the datasheet's state machine diagrams, here's the CONT mode for example.

![image](https://github.com/sparkfun/SparkFun_AS7331_Arduino_Library/assets/101155592/de4392e2-bb6b-4d18-97b4-4f6ed467831a)

You can be in a measurement mode while still in standby. Standby provides faster measurement start than power down mode, but consumes more current than power down and less than idle mode. Since actually beginning a measurement requires a bunch of things, it's good to have levers that control all of them available to the user, but also a convenience factor that does the work for them so all they have to do is just set the startstate=1 and away they go.

2023-12-01 23:43 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +                calculateConversionFactors();
Ah ok, fair enough. Add a comment explaining that

2023-12-01 23:48 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            }
I like it! I'll do just that.

2023-12-01 23:53 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        int8_t setDigitalDivider(const as7331_divider_val_t divider, const bool setEnableDiv = false)
> so they can use it later

That sounds like a very niche use case. I think in 99%+ of use cases, people will just want to set the divider or disable it. Changing it is only a single register write regardless, but the current implementation might actually write to the register twice, which is slow.

Now I'm actually thinking that `setEnableDivider()` and `setDigitalDivider()` could be combined into a single method. Add another value to `as7331_divider_val_t` called something like `DIV_DISABLE`. Then do something like

```
if(divider == DIV_DISABLE)
    creg2.en_div = DIVIDER_DISABLED;
else
{
    creg2.en_div = DIVIDER_ENABLED;
    creg2.div = divider;
}
```

2023-12-01 23:55 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +            *pd = _state.pd;
> good as private/protected methods

Well they're not even used elsewhere in the library, so if you make them private, may as well just delete them.

2023-12-04 15:18 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +            }
Looking at it that won't quite work since fsrX and _conversionX are different for each channel, but I'm going to do something similar.

2023-12-04 16:09 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +                return false;
Agreed, the user should just call `reset()` if they want to reset the device

2023-12-04 16:21 UTC, sfe-SparkFro commented on src/SparkFun_AS7331.h
> +        bool startMeasurement(const as7331_meas_mode_t measMode = MEAS_MODE_CONT, bool startMeasure = false)
Ok, fair enough, let's just rename this function (FWIW I like `prepareMeasurement`)

2023-12-05 23:13 UTC, SFE-Brudnerd commented on src/SparkFun_AS7331.h
> +        int8_t setDigitalDivider(const as7331_divider_val_t divider, const bool setEnableDiv = false)
I like this, but I don't want to add another value to `as7331_divider_val_t` since that's a 1:1 with the register. I'll figure something out.

2023-12-14 00:09 UTC, SFE-Brudnerd commented
Closing for PR into main.

2023-12-14 00:09 UTC, closed without merging